### ISSUE TITLE
Nothing gets drawn with v0.3.18 (and segmentation fault)

### ISSUE THREAD

**Issue by getzen** [not-fl3/macroquad#420] opened 2022-06-13 18:35 UTC
Using an iMac with MacOS v12.4, I created a brand new project in VS Code, added Macroquad as a dependency, and pasted the example text into main.rs:
`use macroquad::prelude::*;

#[macroquad::main("BasicShapes")]
async fn main() {
    loop {
        clear_background(RED);

        draw_line(40.0, 40.0, 100.0, 200.0, 15.0, BLUE);
        draw_rectangle(screen_width() / 2.0 - 60.0, 100.0, 120.0, 60.0, GREEN);
        draw_circle(screen_width() - 30.0, screen_height() - 30.0, 15.0, YELLOW);

        draw_text("IT WORKS!", 20.0, 20.0, 30.0, DARKGRAY);

        next_frame().await
    }
}`

The app runs but all I get is the red background. No line, rectangle, circle, or text.

I have not had a problem with previous Macroquad versions (all good through 0.3.16). Also (and it must be related), with existing, larger projects than ran fine under previous versions of Macroquad, I can't get 0.3.18 to run at all. I get a segmentation fault.

(Is there a way to specify an exact, _earlier_ version of Macroquad in cargo.toml?)

**Comment by not-fl3** [comment] 2022-06-13 18:40
Unfortunately, I can't reproduce it myself, so I can't really promise a fix soon :(  

> (Is there a way to specify an exact, earlier version of Macroquad in cargo.toml?)

```
macroquad = { version = "=0.3.18" }
```

This doc page could help: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#comparison-requirements

**Comment by getzen** [comment] 2022-06-13 18:44
Okay, reverting to 0.3.16 solved the problem, so it's definitely something with 0.3.18.

**Comment by pvlnzmv** [comment] 2022-06-14 13:15
I've had the same issue with versions 0.3.17 and 0.3.18. Version 0.3.16 works perfectly fine.

P.S. I've attached a file containing stack backtrace from running the example program. Please let me know if i can help in any way.
[macroquad_0_3_18_backtrace.txt](https://github.com/not-fl3/macroquad/files/8900012/macroquad_0_3_18_backtrace.txt)
a

**Comment by pvlnzmv** [comment] 2022-06-14 13:28
I've had the similar issue with versions 0.3.17 and 0.3.18 on Mac mini M1 with macOS 12.4, although in my case the example program immediately crashes. Version 0.3.16 works perfectly fine.

P.S. I've attached a file containing stack backtrace from running the example program. Please let me know if i can help in any other way.

[macroquad_0_3_18_backtrace.txt](https://github.com/not-fl3/macroquad/files/8900150/macroquad_0_3_18_backtrace.txt)

**Comment by s-valent** [comment] 2022-06-14 17:08
For me on M1 macbook pro on macOS 12.4 it doesn't crash, it just flickers from black to background color nonstop

**Comment by not-fl3** [comment] 2022-06-14 18:07
This should be fixed in `0.3.19`

**Comment by pvlnzmv** [comment] 2022-06-14 18:11
Just tried version 0.3.19. Works like a charm now. Thank you!

**Closed** 2022-06-14 18:31 UTC
